# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'long_term_recording_parameters_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(408, 214)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(320, 20, 81, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 20, 281, 171))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_36.setObjectName("label_36")
        self.lineEdit_duration = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_duration.setGeometry(QtCore.QRect(100, 30, 31, 20))
        self.lineEdit_duration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_duration.setObjectName("lineEdit_duration")
        self.lineEdit_sleep_time = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_sleep_time.setGeometry(QtCore.QRect(100, 60, 31, 20))
        self.lineEdit_sleep_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_sleep_time.setObjectName("lineEdit_sleep_time")
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setGeometry(QtCore.QRect(150, 60, 61, 16))
        self.label_35.setObjectName("label_35")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_33.setObjectName("label_33")
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(150, 30, 16, 16))
        self.label_37.setObjectName("label_37")
        self.label_folder_to_save_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_folder_to_save_7.setGeometry(QtCore.QRect(10, 100, 61, 23))
        self.label_folder_to_save_7.setObjectName("label_folder_to_save_7")
        self.lineEdit_file_name = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_file_name.setGeometry(QtCore.QRect(70, 100, 181, 20))
        self.lineEdit_file_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_file_name.setObjectName("lineEdit_file_name")
        self.label_folder_to_save_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_folder_to_save_6.setGeometry(QtCore.QRect(170, 130, 101, 23))
        self.label_folder_to_save_6.setObjectName("label_folder_to_save_6")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_4.setTitle(_translate("Dialog", "Lon-term measure options"))
        self.label_36.setText(_translate("Dialog", "Duration"))
        self.lineEdit_duration.setText(_translate("Dialog", "10"))
        self.lineEdit_sleep_time.setText(_translate("Dialog", "10"))
        self.label_35.setText(_translate("Dialog", "s"))
        self.label_33.setText(_translate("Dialog", "Save each "))
        self.label_37.setText(_translate("Dialog", "s"))
        self.label_folder_to_save_7.setText(_translate("Dialog", "File name:"))
        self.lineEdit_file_name.setText(_translate("Dialog", "1"))
        self.label_folder_to_save_6.setText(_translate("Dialog", ".long_dynamics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
