# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printer_parameters_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 248)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 30, 271, 201))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_36.setObjectName("label_36")
        self.lineEdit_IP = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_IP.setGeometry(QtCore.QRect(90, 30, 161, 20))
        self.lineEdit_IP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        self.label_38.setGeometry(QtCore.QRect(10, 32, 101, 16))
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        self.label_39.setGeometry(QtCore.QRect(10, 70, 131, 16))
        self.label_39.setObjectName("label_39")
        self.lineEdit_max_velocity_mm_s = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_max_velocity_mm_s.setGeometry(QtCore.QRect(200, 70, 51, 20))
        self.lineEdit_max_velocity_mm_s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_max_velocity_mm_s.setObjectName("lineEdit_max_velocity_mm_s")
        self.lineEdit_max_accel_mm_s2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_max_accel_mm_s2.setGeometry(QtCore.QRect(200, 100, 51, 20))
        self.lineEdit_max_accel_mm_s2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_max_accel_mm_s2.setObjectName("lineEdit_max_accel_mm_s2")
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        self.label_40.setGeometry(QtCore.QRect(10, 100, 161, 16))
        self.label_40.setObjectName("label_40")
        self.lineEdit_safe_yx_speed_mm_s = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_safe_yx_speed_mm_s.setGeometry(QtCore.QRect(200, 140, 51, 20))
        self.lineEdit_safe_yx_speed_mm_s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_safe_yx_speed_mm_s.setObjectName("lineEdit_safe_yx_speed_mm_s")
        self.label_41 = QtWidgets.QLabel(self.groupBox_4)
        self.label_41.setGeometry(QtCore.QRect(10, 140, 161, 16))
        self.label_41.setObjectName("label_41")
        self.lineEdit_safe_z_speed_mm_s = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_safe_z_speed_mm_s.setGeometry(QtCore.QRect(200, 170, 51, 20))
        self.lineEdit_safe_z_speed_mm_s.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_safe_z_speed_mm_s.setObjectName("lineEdit_safe_z_speed_mm_s")
        self.label_42 = QtWidgets.QLabel(self.groupBox_4)
        self.label_42.setGeometry(QtCore.QRect(10, 170, 161, 16))
        self.label_42.setObjectName("label_42")
        self.label_36.raise_()
        self.lineEdit_IP.raise_()
        self.label_38.raise_()
        self.lineEdit_max_velocity_mm_s.raise_()
        self.label_39.raise_()
        self.lineEdit_max_accel_mm_s2.raise_()
        self.label_40.raise_()
        self.lineEdit_safe_yx_speed_mm_s.raise_()
        self.label_41.raise_()
        self.lineEdit_safe_z_speed_mm_s.raise_()
        self.label_42.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_4.setTitle(_translate("Dialog", "Printer parameters"))
        self.label_36.setText(_translate("Dialog", "IP"))
        self.lineEdit_IP.setText(_translate("Dialog", "10.2.15.109"))
        self.label_39.setText(_translate("Dialog", "max velocity, mm/s"))
        self.lineEdit_max_velocity_mm_s.setText(_translate("Dialog", "200"))
        self.lineEdit_max_accel_mm_s2.setText(_translate("Dialog", "500"))
        self.label_40.setText(_translate("Dialog", "max acceleration, mm*2/s"))
        self.lineEdit_safe_yx_speed_mm_s.setText(_translate("Dialog", "100"))
        self.label_41.setText(_translate("Dialog", "safe xy speed, mm/s"))
        self.lineEdit_safe_z_speed_mm_s.setText(_translate("Dialog", "30"))
        self.label_42.setText(_translate("Dialog", "safe z speed, mm/s"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
