# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recording_parameters_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 206)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(320, 20, 81, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 20, 251, 181))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(160, 110, 16, 16))
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        self.label_36.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_36.setObjectName("label_36")
        self.lineEdit_recording_duration = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_recording_duration.setGeometry(QtCore.QRect(100, 30, 31, 20))
        self.lineEdit_recording_duration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_recording_duration.setObjectName("lineEdit_recording_duration")
        self.lineEdit_write_every_nth = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_write_every_nth.setGeometry(QtCore.QRect(100, 70, 31, 20))
        self.lineEdit_write_every_nth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_write_every_nth.setObjectName("lineEdit_write_every_nth")
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_32.setObjectName("label_32")
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setGeometry(QtCore.QRect(150, 70, 61, 16))
        self.label_35.setObjectName("label_35")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_33.setObjectName("label_33")
        self.lineEdit_rep_rate = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_rep_rate.setGeometry(QtCore.QRect(100, 110, 41, 20))
        self.lineEdit_rep_rate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_rep_rate.setObjectName("lineEdit_rep_rate")
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(150, 30, 16, 16))
        self.label_37.setObjectName("label_37")
        self.checkBox_plot_live_while_recording = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_plot_live_while_recording.setGeometry(QtCore.QRect(10, 150, 171, 17))
        self.checkBox_plot_live_while_recording.setChecked(False)
        self.checkBox_plot_live_while_recording.setObjectName("checkBox_plot_live_while_recording")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_4.setTitle(_translate("Dialog", "Recording options"))
        self.label_34.setText(_translate("Dialog", "Hz"))
        self.label_36.setText(_translate("Dialog", "Duration"))
        self.lineEdit_recording_duration.setText(_translate("Dialog", "10"))
        self.lineEdit_write_every_nth.setText(_translate("Dialog", "10"))
        self.label_32.setText(_translate("Dialog", "Repetition rate"))
        self.label_35.setText(_translate("Dialog", "th frame"))
        self.label_33.setText(_translate("Dialog", "Save each "))
        self.lineEdit_rep_rate.setText(_translate("Dialog", "2000"))
        self.label_37.setText(_translate("Dialog", "s"))
        self.checkBox_plot_live_while_recording.setText(_translate("Dialog", "plot live while recording"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
